/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsPostingRouteImport } from './routes/docs.posting'
import { Route as DocsSetupRouteImport } from './routes/docs.setup'
import { Route as DocsTokensRouteImport } from './routes/docs.tokens'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as ApiPublicHooksAutoPostRouteImport } from './routes/api/public/hooks/auto-post'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPostingRoute = DocsPostingRouteImport.update({
  id: '/posting',
  path: '/posting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSetupRoute = DocsSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTokensRoute = DocsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => DocsRoute,
} as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoPostRoute = ApiPublicHooksAutoPostRouteImport.update({
  id: '/api/public/hooks/auto-post',
  path: '/api/public/hooks/auto-post',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/licenses': typeof LicensesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/docs/posting': typeof DocsPostingRoute
  '/docs/setup': typeof DocsSetupRoute
  '/docs/tokens': typeof DocsTokensRoute
  '/docs/': typeof DocsIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/api/public/hooks/auto-post': typeof ApiPublicHooksAutoPostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/changelog': typeof ChangelogRoute
  '/licenses': typeof LicensesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/docs/posting': typeof DocsPostingRoute
  '/docs/setup': typeof DocsSetupRoute
  '/docs/tokens': typeof DocsTokensRoute
  '/docs': typeof DocsIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/api/public/hooks/auto-post': typeof ApiPublicHooksAutoPostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/licenses': typeof LicensesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/docs/posting': typeof DocsPostingRoute
  '/docs/setup': typeof DocsSetupRoute
  '/docs/tokens': typeof DocsTokensRoute
  '/docs/': typeof DocsIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/api/public/hooks/auto-post': typeof ApiPublicHooksAutoPostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/changelog'
    | '/docs'
    | '/licenses'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/app'
    | '/docs/posting'
    | '/docs/setup'
    | '/docs/tokens'
    | '/docs/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/api/public/hooks/auto-post'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/changelog'
    | '/licenses'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/app'
    | '/docs/posting'
    | '/docs/setup'
    | '/docs/tokens'
    | '/docs'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/api/public/hooks/auto-post'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/changelog'
    | '/docs'
    | '/licenses'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/app'
    | '/docs/posting'
    | '/docs/setup'
    | '/docs/tokens'
    | '/docs/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/api/public/hooks/auto-post'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRouteWithChildren
  LicensesRoute: typeof LicensesRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
  ApiPublicHooksAutoPostRoute: typeof ApiPublicHooksAutoPostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/posting': {
      id: '/docs/posting'
      path: '/posting'
      fullPath: '/docs/posting'
      preLoaderRoute: typeof DocsPostingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/setup': {
      id: '/docs/setup'
      path: '/setup'
      fullPath: '/docs/setup'
      preLoaderRoute: typeof DocsSetupRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tokens': {
      id: '/docs/tokens'
      path: '/tokens'
      fullPath: '/docs/tokens'
      preLoaderRoute: typeof DocsTokensRouteImport
      parentRoute: typeof DocsRoute
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-post': {
      id: '/api/public/hooks/auto-post'
      path: '/api/public/hooks/auto-post'
      fullPath: '/api/public/hooks/auto-post'
      preLoaderRoute: typeof ApiPublicHooksAutoPostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DocsRouteChildren {
  DocsPostingRoute: typeof DocsPostingRoute
  DocsSetupRoute: typeof DocsSetupRoute
  DocsTokensRoute: typeof DocsTokensRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsPostingRoute: DocsPostingRoute,
  DocsSetupRoute: DocsSetupRoute,
  DocsTokensRoute: DocsTokensRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRouteWithChildren,
  LicensesRoute: LicensesRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
  ApiPublicHooksAutoPostRoute: ApiPublicHooksAutoPostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
