/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'
import { Route as ApiPublicHooksAutoPostRouteImport } from './routes/api/public/hooks/auto-post'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoPostRoute = ApiPublicHooksAutoPostRouteImport.update({
  id: '/api/public/hooks/auto-post',
  path: '/api/public/hooks/auto-post',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/api/public/hooks/auto-post': typeof ApiPublicHooksAutoPostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/api/public/hooks/auto-post': typeof ApiPublicHooksAutoPostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/api/public/hooks/auto-post': typeof ApiPublicHooksAutoPostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/api/public/hooks/auto-post'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/api/public/hooks/auto-post'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/app'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/api/public/hooks/auto-post'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
  ApiPublicHooksAutoPostRoute: typeof ApiPublicHooksAutoPostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-post': {
      id: '/api/public/hooks/auto-post'
      path: '/api/public/hooks/auto-post'
      fullPath: '/api/public/hooks/auto-post'
      preLoaderRoute: typeof ApiPublicHooksAutoPostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
  ApiPublicHooksAutoPostRoute: ApiPublicHooksAutoPostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
